## Copias y vistas de arrays

In [3]:
import numpy as np

In [6]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
y = x

In [8]:
y.shape = (2,5)
y

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [9]:
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
#IMPORTANTE, como pudimos ver, cuando creas un array y luego se asignes ese arraya una variable
#NO estas creando un nuevo array, simplemente lo estas REFERENCIANDO
#Por lo que si haces un cambio en y tambien se hara en x

In [10]:
y = x.copy() #Para esto debes hacer un clon del array, utilizando copy
y

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [12]:
y.shape = (5,2)
y

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [13]:
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [14]:
y is x # Puedes tambien comprobarlo utilizando "is"

False

In [21]:
x = np.arange(10)
v = x.view() #View no crea una copia sino una vista, siguen siendo el mismo array pero dejan de compartir propiedades
v

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
v.shape = (5,2) #Este view ahora tiene una forma diferente a su array original
v

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [23]:
x #Pero el array original sigue con su forma original

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])