## Funciones universales (ufunc)
- Unarias: sqrt, sin, cos, **2 (Aplican las transformaciones elemento a elemento)
- Binarias: maximum, minimum (Reciben 2 array y normalmente devuelve un array como resultado)

In [3]:
import numpy as np

In [4]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
x+3 # Operaciones aritmeticas a cada elemento 

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [6]:
x/3 # Operaciones aritmeticas a cada elemento

array([0.        , 0.33333333, 0.66666667, 1.        , 1.33333333,
       1.66666667, 2.        , 2.33333333, 2.66666667, 3.        ])

In [7]:
alpha = np.linspace(0,2*np.pi, 4) #Una serie de angulos generados automaticamente
alpha

array([0.        , 2.0943951 , 4.1887902 , 6.28318531])

In [8]:
np.sin(alpha) #Sacandole el seno a cada elemento del array

array([ 0.00000000e+00,  8.66025404e-01, -8.66025404e-01, -2.44929360e-16])

In [15]:
x = np.arange(10)
np.exp(x)#Elevando el numero "e" al exponente de cada elemento

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [19]:
np.exp2(x) #Elevando el numero "2" al exponente de cada elemento

array([  1.,   2.,   4.,   8.,  16.,  32.,  64., 128., 256., 512.])

In [20]:
np.power(x, 3) #Elevando el numero X elevado a 3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [21]:
np.sqrt(x) #La raiz cuadrada de cada elemento

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [25]:
x = np.arange(1,10)
np.log(x) # Logaritmo base 1 de cada elemento

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [26]:
np.log10(x) # Logaritmo base 10 de cada elemento

array([0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ,
       0.77815125, 0.84509804, 0.90308999, 0.95424251])

In [27]:
np.sum(x) #La suma de todos los elementos

45

In [32]:
np.nansum(x) #La suma de todos los elementos (Version eliminando valores NaN )

45

In [29]:
np.prod(x) #El producto de todos los elementos

362880

In [30]:
np.mean(x) #Calcular el media

5.0

In [31]:
np.median(x) #Calcular la mediana

5.0

In [33]:
np.min(x)

1

In [34]:
np.max(x)

9

In [36]:
np.std(x) #Calcular la desviacion tipica

2.581988897471611

In [37]:
np.var(x) #Calcular la varianaza

6.666666666666667

In [39]:
np.argmin(x) #La POSICION del valor mas pequeño

0

In [40]:
np.argmax(x) #La POSICION del valor mas grande

8

In [41]:
np.percentile(x, q=0.95) #El percentil del quantil exacto que quieres calcular

1.076

In [43]:
y = (x<5)
y

array([ True,  True,  True,  True, False, False, False, False, False])

In [44]:
np.any(y) # COmprueba si al menos UNO de los valores es True

True

In [47]:
np.all(y) # COmprueba si TODOS los valores son True

False

In [76]:
np.random.seed(2019) #Para generar siempre los mismos numeros aleatorios en base al criterio dado en la semilla
z = np.random.random((3,5,4))#Esto genera 3 filas y 5 columnas de datos aleatorios
z

array([[[0.90348221, 0.39308051, 0.62396996, 0.6378774 ],
        [0.88049907, 0.29917202, 0.70219827, 0.90320616],
        [0.88138193, 0.4057498 , 0.45244662, 0.26707032],
        [0.16286487, 0.8892147 , 0.14847623, 0.98472349],
        [0.03236122, 0.51535075, 0.20112905, 0.88601087]],

       [[0.51361992, 0.57830159, 0.29928265, 0.8371974 ],
        [0.52664983, 0.10484424, 0.27812941, 0.04659494],
        [0.50907615, 0.47242629, 0.90448733, 0.94349222],
        [0.70339235, 0.84629795, 0.92799464, 0.81936188],
        [0.84518556, 0.79145187, 0.17100016, 0.28997792]],

       [[0.30448392, 0.1476601 , 0.57381853, 0.86355701],
        [0.32329947, 0.27564943, 0.68218738, 0.19140631],
        [0.58102448, 0.86255827, 0.23452664, 0.28985187],
        [0.38285364, 0.34960393, 0.32879374, 0.94017484],
        [0.0380261 , 0.77684511, 0.38464466, 0.71672375]]])

In [77]:
z.sum()

31.826718933498338

In [73]:
z.sum(axis=0) #Axis=0 Hace las sumas por columnas

array([[1.72158605, 1.11904219, 1.49707115, 2.33863182],
       [1.73044837, 0.67966568, 1.66251506, 1.14120741],
       [1.97148256, 1.74073435, 1.5914606 , 1.50041441],
       [1.24911086, 2.08511657, 1.40526461, 2.74426021],
       [0.91557288, 2.08364773, 0.75677386, 1.89271255]])

In [74]:
z.sum(axis=1) #Axis=1 Hace las sumas por filas

array([[2.8605893 , 2.50256777, 2.12822012, 3.67888824],
       [3.09792381, 2.79332194, 2.5808942 , 2.93662437],
       [1.62968761, 2.41231682, 2.20397096, 3.00171378]])

In [75]:
z.sum(axis=2) #Axis=2 Hace las sumas por profundidad, La tercera dimension

array([[2.55841008, 2.78507552, 2.00664867, 2.18527928, 1.63485189],
       [2.22840156, 0.95621841, 2.82948199, 3.29704683, 2.09761552],
       [1.88951956, 1.47254259, 1.96796126, 2.00142615, 1.91623962]])