## Numpy

In [9]:
import numpy as np
# Otro metodo es: "from numpy import *" 
#Con este metodo no tendreis que estar usando np cada vez que quieras usar una funcion de numpy 
#Pero este metodo no es recomendable ya que el nombre de una funcion de numpy puede concidir con una funcin tuya 

In [11]:
l = [1,2,3,4,5,6,7,8,9,10]
l = np.array(l) # Conviertes una lista en un array
l

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
l = [1,2,3,4,5,6,7,8,9,10]
l = np.array(l,dtype='float32') # Puedes declarar el tipo de datos
l

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float32)

##### Los tipos de datos numericos en python 
- bool_
- int_, intc, intp, int8, int16, int32, int64
- uint8, uint16, uint32, uint64
- float_, float16, float32, float64 (+/-999.9999999e99999)
- complex_, complex64, complex128 (a+bi, a,b $\in$ float_) 

In [16]:
np.zeros((3,4)) # Para sacar una matriz de ceros de 3 filas y 4 columnas

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [19]:
np.ones((4,3))# Para sacar una matriz de unos de 3 filas y 4 columnas

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [18]:
np.arange(10) # Para crear arrays de forma secuencial hasta x numero

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
np.arange(3,12,dtype=np.float) # Para crear arrays de forma secuencial de x numero hasta x numero, y puedes definir el dtype

array([ 3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [22]:
np.arange(4,5.1,0.1) # Para crear arrays de forma secuencial de x numero hasta x, definiendo los "saltos"

array([4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. ])

In [23]:
np.linspace(1., 7., 12) # Para crear un array de un numero x hasta y PERO que la secuencia se divida en z elementos

array([1.        , 1.54545455, 2.09090909, 2.63636364, 3.18181818,
       3.72727273, 4.27272727, 4.81818182, 5.36363636, 5.90909091,
       6.45454545, 7.        ])

In [24]:
np.eye(5) # Para crear una matriz de identidad 5, osea 5x5 con una diagonal de unos 

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [25]:
x = np.arange(24) # Para crear un array
x.reshape((6,4)) # Para cambiar la forma de una matriz, en este caso de una matriz 6x4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [26]:
x = np.array([[1,2,3,4], [5,6,7,8]])
x
np.ravel(x) # Esta funcion aplana una matriz, osea lo lleva a una fila

array([1, 2, 3, 4, 5, 6, 7, 8])

In [27]:
x.flatten() # Hace lo mismo que ravel pero hace una copia de la matriz, ravel afecta la misma matriz

array([1, 2, 3, 4, 5, 6, 7, 8])

In [28]:
np.transpose(x) #Transpone una matriz

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [29]:
np.resize(x, (5, 3)) #Crea una nueva matriz con la forma que le indiques, en este caso lo lllevo a 5x3
# Si tiene mas elementos del array original, los repetira

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 1],
       [2, 3, 4],
       [5, 6, 7]])

## Ejercicios

- Crear un array de datos con valores entre 5 y 120.
- Crear una matriz 4x4 con los valores desde 0 hasta 15.
- Crear la identidad 7x7
- Crear un array de 20 elementos y transformarlos en una matrix 5x4
- Crear un array con 20 números con los valores entre 0 y 5 espaciados de forma uniforme



In [30]:
np.arange(5,121)

array([  5,   6,   7,   8,   9,  10,  11,  12,  13,  14,  15,  16,  17,
        18,  19,  20,  21,  22,  23,  24,  25,  26,  27,  28,  29,  30,
        31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,  42,  43,
        44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,  56,
        57,  58,  59,  60,  61,  62,  63,  64,  65,  66,  67,  68,  69,
        70,  71,  72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,
        83,  84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,
        96,  97,  98,  99, 100, 101, 102, 103, 104, 105, 106, 107, 108,
       109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120])

In [31]:
x = np.arange(0,16)
np.resize(x, (4, 4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [33]:
np.eye(7) 

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [35]:
x = np.arange(1,21)
np.resize(x, (5, 4))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [45]:
np.linspace(0, 5, 20)

array([0.        , 0.26315789, 0.52631579, 0.78947368, 1.05263158,
       1.31578947, 1.57894737, 1.84210526, 2.10526316, 2.36842105,
       2.63157895, 2.89473684, 3.15789474, 3.42105263, 3.68421053,
       3.94736842, 4.21052632, 4.47368421, 4.73684211, 5.        ])